/* SVN header
$Date: 2018-03-15 12:39:34 +0100 (to, 15 mar 2018) $
$Revision: 93 $
$Author: FCNI6683 $
$Id: timeAtRisk.sas 93 2018-03-15 11:39:34Z FCNI6683 $
*/
%MACRO TimeAtRisk(startdate,endpoints,scale=365.25);
    /*
Dette program laver beregner Days At Risk for endepunkt variablene.
    startdate: datevariable start of risk period.
    endpoints: prefix of endpoint varables, generated by %genEndpoints;
scale : scale day at risk
ex:
    data test;
	merge MasterData.pop MasterData.charlson;
	by pnr;
	vital=(doddato>.);
        startdt='23dec1993'd;
        %genENdpoint(Death,doddato,doddato,deadcode=vital=1,studyenddate='01jan2000'd);
        %genEndpoint(s12,S1date S2date,doddato,deadcode=vital=1,studyenddate='01jan2000'd);
        %genEndpoint(s12d,S1date S2date,doddato,deadcode=vital=1,studyenddate='01jan2000'd,combined=TRUE);
        %TimeAtRisk(startdt,s12 s12d);
        keep pnr s1date s2date s12enddate s12status s12denddate s12dstatus deathenddate deathstatus deathTAR s12TAR s12dTAR ;
    run;
*/
    %let elstcnt = %sysfunc(countw(&endpoints));
    %DO I=1 %to &elstcnt;
        %let eval =%sysfunc(compress( %qscan(&endpoints,&i)));
        &eval.TAR = ( &eval.EndDate - &startdate )/&scale;
        label &eval.TAR="Time at risk for endpoint &eval, pr &scale days";
        %end;
    %MEND;
